apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k200353/waleed_test_backend:latest  #Change This
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"  # Example: 500m CPU request
          limits:
            cpu: "1"     # Example: 1 CPU limit
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
